name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install SQLite3
        run: sudo apt install -y libsqlite3-dev
      - name: Install MoonBit CLI
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> "$GITHUB_PATH"
      - name: Moon update
        run: moon update
      - name: Moon check (native)
        run: moon check --deny-warn --target native
      - name: Moon check (js)
        run: moon check --deny-warn --target js
      - name: Moon info
        run: |
          moon info --target native
          git diff --exit-code
      - name: Format check
        run: |
          moon fmt
          git diff --exit-code
      - name: Moon test (native)
        run: moon test --target native
      - name: Moon test (js)
        run: moon test --target js
